import { useAuth } from '../contexts/auth'

import Head from 'next/head'
import Login from '../components/Login'
import Logout from '../components/Logout';
import Signup from '../components/Signup';
import Dashboard from '../components/Dashboard';

export default function Home() {

  const { user, login, logout } = useAuth();

  return (
    <div>
      <Head>
        <title>Task Organizer</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main>
        {user ? <><Logout logout={logout} /> <Dashboard user={user} /></> : <> <Login login={login} /> <Signup login={login} /> </>}
      </main>

      <footer>

      </footer>
    </div>
  )
}
