import Head from 'next/head'
import Profile from '../components/Profile';
import Sidebar from '../components/Sidebar';

export default function profile() {

    return (
        <div>
            <div>
                <Head>
                    <title>Task Organizer</title>
                    <meta name="description" content="Generated by create next app" />
                    {/* <link rel="icon" href="/favicon.ico" /> */}
                </Head>
            </div>

            <main>
                <> <Sidebar /> <Profile /></>
            </main>

            <footer>

            </footer>
        </div>
    );
}
